### ISSUE TITLE
Create PGA Logo

### ISSUE THREAD

**Issue by 3manuek** [postgres-anywhere/pga.sh#1]
[Reference](https://github.com/postgres-anywhere/pga/issues/18)

Tracking work about site assets that require design.

**Comment by lgarciaog** [comment]
Here's the PGA logo, font pairing, color scheme and suggested icons in both, light and dark mode:

![image](https://github.com/postgres-anywhere/pga.sh/assets/67052413/b0116f99-cf41-4ee9-a1e5-a2597a7fd9b9)

![image](https://github.com/postgres-anywhere/pga.sh/assets/67052413/ac34a09e-08e0-4ce4-8b02-b10b9772a6a8)
