### ISSUE TITLE
Styling improvements

### ISSUE THREAD

**Issue by ahachete** [postgres-anywhere/pga.sh#11]
Here are some _detallitos_ from my PoV. Note that some of them are more on the "let's please try that and I'd also like to hear your opinion" more than "let's do this". Feel free to comment/demo before making a final decision --specially if any of these item may require notable effort, even though I think they are all pretty light adjustments here and there.

* [x] The "Star on Github", "Join our Slack" buttons need to be green-ed? I think we can use the "original" ones. They look a bit weird to me when green-ed, and TBH a bit more color may not hurt. But maybe I'm also wrong here and they would look bad. But worth a try from my PoV.
* [x] There's too much padding/margin IMO around the `PGA Containers` title, both on top and the bottom. I'd make it much smaller, so that we get the box with the URL sit at a position in the top of the page. Now it renders almost in the middle.
* [x] The `Image` title of the toggle `canonical | digest` is left-aligned with the toggle, can it be right-aligned?
* [x] I'd reconsider / would like to try moving Patroni below Postgres selector. After all, there will be in the future several such "sections", not only two, and I think it makes the current area too crowded. So even if it means a bit more vertical scrolling, I'd try this. This would also allow the Patroni version to be always present (even though should be disabled if the toggle is on `Disable`).
* [x] I'd like to see the `Command` and `Image` toggles sit below the url bar. I'd like to see the url bar more on top, and I think it makes more sense to see the toggles below. We could also save vertical space if the title of the toggles is in the same line as the toggles, i.e. something like
    `Command  | pull | run |                   ...                   | canonical | digest |  Image`.
* [x] I'd review the font sizes. There seems to be a bit of a mix across all components. Related: `Image details` content seems to be too small font for me, I'd enlarge it slightly.
* [x] I'd remove the scroll bar in the extensions section. It makes a bit of sense, but it creates double scrolling in the web page, and for me that's not ergonomic. I prefer always "page level" scrolling only.
* [x] The `Extensions` selector has a box around. I'd expect the same for the `Postgres` and `Patroni` (and every section), specially if as requested above these last two will be split in "horizontal sections", one below the other one.
* [x] The version dropdown for the extensions clutters a bit the view, it's too much information (when most of the people almost always would want the latest version of the extension). I'd say we either keep it as is but add "`default`" (without the version it corresponds to, in this case) as the first option and the one that obviously shows by default; or we move the version to the right of `Description` (I think this is good anyway) and then remove the dropdown (keep the value) if there's only one version available --that is, we transform the dropdown into a plain text value. I think this will make it leaner.
* [x] The " Select the extensions you would like to install" text below the extensions has little to no utility. I think a tooltip might be better for this kind of information, but I'd add one, consistently, to every section. Here are the copy for each tooltip:
    * `Postgres`:  Select the version of Postgres that will contain the image. You may select a label like `latest` for the latest major and minor version, or a label like `15.latest` that will select the latest minor version for Postgres 15.
    * `Patroni`: Add a Patroni (https://patroni.readthedocs.io) layer to the image, to implement high availability. You may select "latest" or any other Patroni version available.
    * `Extensions`: add as many extensions as you want for your Postgres image. Note that all extensions are specifically compiled against the Postgres major and minor version selected. Some extensions may have more than one available version.
* [x] The page lacks a footer IMHO. We can start with a simple footer with the usual "Made with :heart: by OnGres" but maybe we should also consider a more standard footer with room for some usual links.
* [x] The Image Details title is outside of the box, whereas every other box has the title inside of it. I'd make this consistent, making also the Image Details box aligned with the Postgres Version box. Also, the image details box border is green, while others are grey/blue-ish, and green is also used for components within the box. I'd also make this consistent by making Image Details Box grey/blue-ish. See screenshot:
![image](https://github.com/user-attachments/assets/fd4c4331-a2da-447e-89cd-1d3a2ebf6abd)
* [x] The `(i)` icon for the tooltip seems to do nothing. Implement.

**Comment by lgarciaog** [comment]
> The "Star on Github", "Join our Slack" buttons need to be green-ed?

Not necessarily, but in reality, the github star is just a white star so we would only have a single coulored icon, Slack, and TBH I don't see any value in that other than making the website "less green" (even though all links on the site are obviously green). To give it a bit of balance, I left the links' text in white (see img)

<img width="446" alt="image" src="https://github.com/user-attachments/assets/a43d4303-3954-4556-89f3-801f85bc0b7d" />

**Comment by lgarciaog** [comment]
About this...
> The version dropdown for the extensions clutters a bit the view... 


<img width="729" alt="image" src="https://github.com/user-attachments/assets/b06be0c3-0352-428e-9e10-b9fbce9678e8" />


As shown in the image, I partially implemented your suggestions but I'll leave a couple of comments... 

> I'd say we either keep it as is but add "default" (without the version it corresponds to, in this case) as the first option and the one that obviously shows by default

Followed your suggestion, but to me it feels way more strange to have a full set of dozens of dropdowns, all of them with the same value ("Default"). TBH, I don't see any added value in such change.

> or we move the version to the right of Description (I think this is good anyway) and then remove the dropdown (keep the value) if there's only one version available --that is, we transform the dropdown into a plain text value. I think this will make it leaner.

I don't see why moving the versions to the right would improve the UX, but I followed your suggestion nevertheless.

Now, if you're worried about clutter, I believe that having a mix of dropdowns with "plain text values" would be worst. It wouldn't be obvious to users why there is one or the other, they would have to explicitly scroll to find a extension with more than one version and interact with it to –hopefully- understand the difference.

**Comment by ahachete** [comment]
TBH I'm not sure what it's best. Let me clarify the "tensions" that I see, to see if this can guide us to the best solution:
* Most of the time, I want to have the "latest" version of the extension. For this I'd like to do nothing (so that the latest is always selected by default; this is how it works now). Now how do we show this? Do we explicitly call out what version that is? Do we say "default" as now, or maybe "latest" to be consistent with the Postgres and Patroni labels?
* Most of the time, extensions only have one version available. If so, having a dropdown for them sounds not ideal, since it "incites" me to click, when there's no possible action to take. And on top, I think it creates too many dropdowns (which are not necessary) that IMO clutter (make it heavier) the UI.
* But if I want to opt for another version, I should have the way to do so.

Maybe we should just show the extension version as a text (as in `default (1.2.3)`) and if and only if there are other versions, to have a dropdown with "other versions" or something like this.

Any other idea/solution taking into account all these facts @lgarciaog ?

**Comment by ahachete** [comment]
> Although I think it's nicer to have the dropdown on the right (or, all the way to the left as well), I agree with @lgarciaog that all of the dropdowns with "Default" doesn't add much and it doesn't look nice.
> 
> Personally, I'd just make the dropdown show the version. It'll default to the default version anyway. And you can also show it as a "disabled dropdown" set at a certain version if that's the only version available.

OK, let's try this, but let's try also to move the version next to the name (right now it's a bit confusing that there are two arrows so close together, being the second one that of the "expand details"). So to summarize, here's what I'd propose:
* Move the Version to be the second/third column, to the right of the name.
* It's always a dropdown, but if there's only one selection possible, it's disabled.
* The version it shows by default is the numeric equivalent of "latest".

**Comment by ahachete** [comment]
Please note @lgarciaog that I have added an additional styling item to the issue's description.

**Comment by jjmaestro** [comment]
> The (i) icon for the tooltip seems to do nothing. Implement.

Not only that, it doesn't render in my browser!? I was wondering what was that stuff 😅 
![image](https://github.com/user-attachments/assets/86a1160a-1b49-40d4-8288-9074e0ce26f9)

**Comment by ahachete** [comment]
> > The (i) icon for the tooltip seems to do nothing. Implement.
> 
> Not only that, it doesn't render in my browser!? I was wondering what was that stuff 😅

Certainly, this is something to review and fix.

In any case, as we may plan the path for production release, we should start considering how to check for wider browser compatibility. For example, I noticed that there's no space between the start and Slack icons and their text in the header on my browser, while a screen capture upthread from you @lgarciaog shows a much better styled combination.

![image](https://github.com/user-attachments/assets/9e879d5b-852e-4876-8d36-fdb8fe5efaf9)

Firefox 133.0 (64-bit), Ubuntu

Feel free to open a separate issue to discuss wider browser testing. For now let's just polish these minor details that are already identified. Thanks!

**Comment by lgarciaog** [comment]
The tooltip works fine on my end, it's a browser native feature so nothing to code there, you just have to hover on the icon (see img)

<img width="737" alt="image" src="https://github.com/user-attachments/assets/9ea90ceb-c377-4553-bee5-ea3d707ce3a1" />

Included the footer and applied the requested changes to the image details section, everything should be done now.

**Comment by ahachete** [comment]
Excellent!

Reviewed and I consider everything done, let's plan next steps!

Great job, closing this issue.
