### ISSUE TITLE
Show extensions that are unavailable (but known to PGA)

### ISSUE THREAD

**Issue by ahachete** [postgres-anywhere/pga.sh#13]
Once I select a Postgres major+minor version, I get a selection of all the extensions that are available for this particular major+minor version. This is great.

However, I'd also like to see which extensions are available for other versions. The use case is if I'm searching for an extension and I don't find it on the list, I don't know if PGA is completely unaware of this extension, or rather it's only available for other versions. If the latter, maybe that extension itself may trigger me to select another major+minor version, because maybe that extension is more important for me than the Postgres version, on which I may compromise.

How to implement this is open for discussion. From a web UI PoV, we could either show unavailable extensions in the proper alphabetical order, but "disabled" and showing a description similar to "This extension is not available for ${flavor} ${flavorMajor}.{flavorMinor}" or similar; or after showing all available extensions, showing a list of all extensions that are not available for this combination.

Bonus point if we can also show on which other Postgres version unavailable extensions are available.

Let's discuss the UI/UX first before committing to a REST endpoint design (even though they could be implemented differently, but at least would serve as initial guidance).

WDYT @lgarciaog ?

**Comment by lgarciaog** [comment]
This has been implemented on #24. Closing!
