### ISSUE TITLE
Add SHA to "Image Details" box

### ISSUE THREAD

**Issue by jjmaestro** [postgres-anywhere/pga.sh#15]
I think it would be useful to always have the SHA visible in the "Image Details" box.

**Comment by jjmaestro** [comment]
> Isn't it enough having it with the Digest button on the right of the URL bar?

It's obvious yeah, but I think it's valuable to have it always visible as well.

> The main problem with the image digest in the details box, is that it will require a lot of wrapping.

True...  but since the font is quite small anyway, maybe there's a way to display the digest split in half, in two lines. Then, it'll always be those two lines.

Anyway, it's more a suggestion, I just think it's nice to have it in there as well, but it's true that it can probably make things ugly XD

**Comment by ahachete** [comment]
> True... but since the font is quite small anyway

I actually proposed in #11 to make fonts more consistent in size (which among others means making this font slightly bigger).

> Anyway, it's more a suggestion, I just think it's nice to have it in there as well, but it's true that it can probably make things ugly XD

This is a bit my though, I don't disagree with the idea, but I'd like to keep the UI as lean as possible (and given that this information is already available elsewhere, I'd opt to keep it there only).

**Comment by jjmaestro** [comment]
Cool, closing it then! :)
