### ISSUE TITLE
Weird "filter extension" bug

### ISSUE THREAD

**Issue by jjmaestro** [postgres-anywhere/pga.sh#16]
Here's a pretty weird bug I just found!

Basically, the "No extensions have been found" and the table header seem to appear/disappear as I move the cursor across the characters in the "filter extensions" and, depending on whether there's a match or not, different things happen / break in different ways 🤣 

I've recorded it in a video because it's pretty hard to explain what's going on 😅

https://github.com/user-attachments/assets/848d1df9-67ef-434f-94dd-6105cde1d360

**Comment by lgarciaog** [comment]
Fixed on #21
