### ISSUE TITLE
"Command" and "Image" buttons together?

### ISSUE THREAD

**Issue by jjmaestro** [postgres-anywhere/pga.sh#18]
Current:
![pga-command-image-buttons](https://github.com/user-attachments/assets/6ffef238-e05f-40e2-bac5-ebe2e338276e)

Maybe better?

![pga-command-image-buttons](https://github.com/user-attachments/assets/dead3230-a456-4d72-ab12-1336fbb06028)

![pga-command-image-buttons](https://github.com/user-attachments/assets/1fdb2204-6801-4d25-9aa6-3a61ce96848d)

Clicking the buttons without having to move the mouse "all the way across the screen"

**Comment by ahachete** [comment]
I think it makes more sense. OTOH, as stated on the 5th item on #11 , I proposed to move these buttons below and on a single "line" (to save on vertical space). So now my thinking would be to combine this all. WDYT?

**Comment by jjmaestro** [comment]
Yeah, I like that. I'll make a mock of this later and will add it here!

**Comment by jjmaestro** [comment]
Alright, here we go!

![pga-URL_Bar](https://github.com/user-attachments/assets/8c8f075c-942d-4c85-90be-c712b0bc193c)

I think it looks much better, yeah :)  And the toggles can be together on the left/right side, as this mock, or maybe centered.

Also, they can be shorter, I've only copy-pasted the buttons and moved them around in GiMP XXD  Maybe I'll try with a PR and changing the CSS... it's been YEARS since I've done any frontend 😅

**Comment by ahachete** [comment]
> OK, I got a PR ready but... I don't have permissions in the repo XXD
> 

Permissions, granted.

I think this is the way to go. Thank you for going as far as PR-ing it!! 

I have a _detallito_ ;) The space between the title of the toggle and the toggle; and between the two toggles, seems very similar. I'd prefer if toggle title and toggle have a smaller space in between than the space in between groups. To do so, the space between `Command|Image` and their toggle could be reduced; the space between the first toggle and `Image` increased; or a combination of both.

Maybe we can also consider (in addition to the above) horizontally centering all these four elements. Maybe it will look better (but not sure).

**Comment by jjmaestro** [comment]
Here's the *detallito* 😝 

![image](https://github.com/user-attachments/assets/c8cc1d30-b116-4af8-882e-372e3668b635)

And, same but centered:

![image](https://github.com/user-attachments/assets/6f7afd8a-038b-4e20-b067-962a74dfad28)

Looking at the overall layour, I think it looks better left-aligned but I'll have the CSS to center commented out so it'll be easier to try it out.

I'll push the PR :)

**Comment by ahachete** [comment]
Yay, thanks!
