### ISSUE TITLE
Adjustments on extensions response for /image-url endpoint

### ISSUE THREAD

**Issue by lgarciaog** [postgres-anywhere/pga.sh#4]
While testing the `/image-url` endpoint from the UI, I found out that the response shows the extension versions and sizes nested inside different parent objects.

The version comes in `image.flavorVersions[$flavorIndex].extensions[$extIndex].version` while the size comes in `imagePlatforms[$platformIndex].flavorVersions[$flavorIndex].extensions[$extIndex].size`.

I think both properties should be included inside the same parent object.

**Comment by ahachete** [comment]
Indeed. Here's a sample response:

```json
{
  "url": "42.pga.sh/pga/postgres--16.3/e/timescaledb",
  "urlDigest": "42.pga.sh/pga@sha256:1ea341e1c8bdacda346b4a9ae6d1bde085bb31527a7f3234bc224e1d8c3ae3e9",
  "image": {
    "base": {
      "name": "ubi",
      "majorVersion": "9",
      "minorVersion": "4"
    },
    "tshirtSize": "s",
    "flavorName": "postgres",
    "flavorAndBaseOmmitted": false,
    "flavorVersions": [
      {
        "majorVersion": "16",
        "minorVersion": "3",
        "addons": [],
        "extensions": [
          {
            "name": "timescaledb",
            "version": "2.13.0"
          }
        ]
      }
    ]
  },
  "imagePlatforms": [
    {
      "os": "linux",
      "architecture": "amd64",
      "base": {
        "revision": "11",
        "size": 9786033
      },
      "flavorVersions": [
        {
          "majorVersion": "16",
          "minorVersion": "3",
          "revision": "12",
          "size": 39335130,
          "addons": [],
          "extensions": [
            {
              "name": "timescaledb",
              "revision": "10",
              "size": 2075122
            }
          ]
        }
      ]
    }
  ]
}
```

I consider there's a bit of redundancy. Sure, this is (possibly) a side effect of reusing existing objects (records) to produce a fast first version --and that's more than fine. But now we have the chance to review and we should reconsider.

At first sight, I thought of proposing the following:

```json
{
  "url": "42.pga.sh/pga/postgres--16.3/e/timescaledb",
  "urlDigest": "42.pga.sh/pga@sha256:1ea341e1c8bdacda346b4a9ae6d1bde085bb31527a7f3234bc224e1d8c3ae3e9",
  "platforms": [
    {
      "os": "linux",
      "architecture": "amd64",
      "image": {
        "base": {
          "name": "ubi",
          "majorVersion": "9",
          "minorVersion": "4",
          "revision": "11",
          "size": 9786033
        },
        "tshirtSize": "s",
        "flavorName": "postgres",
        "flavorAndBaseOmmitted": false,
        "flavorVersions": [
          {
            "majorVersion": "16",
            "minorVersion": "3",
            "revision": "12",
            "size": 39335130,
            "addons": [],
            "extensions": [
              {
                "name": "timescaledb",
                "version": "2.13.0",
                "revision": "10",
                "size": 2075122
              }
            ]
          }
        ]
      }
    },
    {
      // other platforms, if any
    }
  ]
}
```

Sure thing, if there are multiple platforms, a lot of fields are also repeated under this structure. And this structure seems to allow behaviors that we shouldn't have (e.g. having different versions in different architectures; but we won't allow that to happen, so it's kind of fine). But it provides "information locality", where all the information needed is in the same subobject.

But this structure is not good either, as it doesn't answer the general questions about the flavor(s) or extension names of the image, which are independent of platform too (and the current one addresses).

Instead, we may want to consider adding the platform-dependent content to a separate structure, but use a more flat structure *and references* to other parts of the document to simplify getting the information, as in:

```json
{
  "url": "42.pga.sh/pga/postgres--16.3/e/timescaledb",
  "urlDigest": "42.pga.sh/pga@sha256:1ea341e1c8bdacda346b4a9ae6d1bde085bb31527a7f3234bc224e1d8c3ae3e9",
  "image": {
    "base": {
      "name": "ubi",
      "layer": "ubi-9.4",
      "majorVersion": "9",
      "minorVersion": "4"
    },
    "tshirtSize": "s",
    "flavorName": "postgres",
    "flavorAndBaseOmmitted": false,
    "flavorVersions": [
      {
        "layer": "postgres-16.3",
        "majorVersion": "16",
        "minorVersion": "3",
        "addons": [],
        "extensions": [
          {
            "name": "timescaledb",
            "layer": "timescaledb-2.13.0",
            "version": "2.13.0"
          }
        ]
      }
    ]
  },
  "platforms": [
    {
      "os": "linux",
      "architecture": "amd64",
      "layers": [
        {
          "name": "ubi-9.4",
          "revision": "11",
          "size": 9786033
        },
        {
          "name": "postgres-16.3",
          "revision": "12",
          "size": 39335130
        },
        {
          "name": "timescaledb-2.13.0",
          "revision": "10",
          "size": 2075122
        }
      ]
    }
  ]
}
```

Note that an additional field has been introduced, named `layer`, which is supposed to be a unique identified, which could be constructed with the layer name (base name, flavor name, extension name, etc) and the version. Could also be an `id`, but I prefer the clearer naming.

This structure also allows for a clear delimitation of what are the layers of the image; something that is important to show the user a tree-like (or pie chart or similar) diagram of the space contributed by each layer.

Parsing of this structure may or may not be trivial, depending on the language/framework. The `layer` field needs to be read within the `image` subobjects; and then this value used as a key lookup of elements within the `platform[]` for objects with that `.name` property matching the value. But if this is ergonomic enough, it provides very direct way to locate the revision and size, concepts with are platform-dependent.

It's still not perfect in that constructing the tree of layers implies understanding that under a given flavor there's an array of extensions. But I think this may be OK-ish.

**Comment by teoincontatto** [comment]
> Instead, we may want to consider adding the platform-dependent content to a separate structure, but use a more flat structure and references to other parts of the document to simplify getting the information, as in: ...

The initial idea for locality was ease of use but locality introduce duplication and allow generating wrong output  (different versions for each platform). On the other side the proposed approach that avoid duplication of data (but duplication of structure) and forbid generating wrong output (that IMHO is very similar to the current implementation with some lifting) still requires lookups to access a platforms specific layers. Here I propose an alternative approach that tries to fix both:

```json
{
  "url": "42.pga.sh/pga/postgres--16.3/e/timescaledb",
  "urlDigest": "42.pga.sh/pga@sha256:1ea341e1c8bdacda346b4a9ae6d1bde085bb31527a7f3234bc224e1d8c3ae3e9",
  "platforms": [
    {
      "name": "linux/amd64",
      "os": "linux",
      "architecture": "amd64"
    }
  ],
  "image": {
    "base": {
      "name": "ubi",
      "majorVersion": "9",
      "minorVersion": "4",
      "layers": {
        "linux/amd64": {
          "revision": "11",
          "size": 9786033
        }
      }
    },
    "tshirtSize": "s",
    "flavorName": "postgres",
    "flavorAndBaseOmmitted": false,
    "flavorVersions": [
      {
        "majorVersion": "16",
        "minorVersion": "3",
        "layers": {
          "linux/amd64": {
            "revision": "12",
            "size": 39335130
          }
        },
        "addons": [],
        "extensions": [
          {
            "name": "timescaledb",
            "version": "2.13.0",
            "layers": {
              "linux/amd64": {
                "name": "timescaledb-2.13.0",
                "revision": "10",
                "size": 2075122
              }
            }
          }
        ]
      }
    ]
  }
}
```

This model offer a lower duplication of structure/data. The `layers` substructure is organized like an hash map so that accessing the layer for a specific platform is done by using the `name` of the platform. @lgarciaog Does that solve your need for the ease of use of the data structure?

> flavor*: shouldn't we make them an object, as in

:+1: 

> Note that I also removed the flavorAndBaseOmmitted field. Can we do without it, and instead computing it from the concept that base and flavor fields are missing, i.e. not present?

The `flavorAndBaseOmmitted` is just informative since it is part of the request. The calculation of total may be affected by this parameter when a partial image is generated. We may remove the flag but then we should also skip the base and flavor layers when generating the partial images.

**Comment by teoincontatto** [comment]
Also, to join all the related refactor of /image-url endpoint I would like to propose a change for the request payload model.

Currently the /image-url request has a payload model that allow a list of flavorVersions and, spearately, a list of extensions. This is fundamentally wrong since a user may request an image with different version of extensions for each version of the flavor. This is particularly true for core and contrib extensions that are versioned alongside the version of Postgres.

I propose to move the extensions array inside of the flavorVersions array, and, following the above discussion, to move the flavor related fields in a specific section called `flavor`:

```json
tshirtSize: <string>
flavorAndBaseOmmitted: <boolean>
base:
  name: <string>
  majorVersion: <string>
  minorVersion: <string>
  revision: <string>
flavor:
  name: <string>
  versions:
  - majorVersion: <string>
    minorVersion: <string>
    revision: <string>
    extensions:
    - name: <string>
      version: <string>
      revision: <string>
addons:
- name: <string>
  version: <string>
  revision: <string>
```

**Comment by ahachete** [comment]
> This model offer a lower duplication of structure/data. The `layers` substructure is organized like an hash map so that accessing the layer for a specific platform is done by using the `name` of the platform. @lgarciaog Does that solve your need for the ease of use of the data structure?

I like it. It's a good idea and :+1: from my PoV, subject to @lgarciaog confirming it's also convenient.

I have just one concern: the hash map. Having dynamic keys is not convenient on some languages (e.g. Java) as keys are not predictable (sure, it's doable, but not ideal). We can either leave it as-is, or nest them into a proper object with a fixed key as in:

```json
{
  "layers": [
    "name": "linux/amd64",
    "data": {
      "revision": "11",
      "size": 9786033
    },
    ...
  ]
}
```

Note that `name` and `data` here could be renamed if desired. While I lean towards this solution with fixed keys, I don't really have a horse in this race. Decide among you too what you prefer.

**Comment by ahachete** [comment]
> The `flavorAndBaseOmmitted` is just informative since it is part of the request. The calculation of total may be affected by this parameter when a partial image is generated. We may remove the flag but then we should also skip the base and flavor layers when generating the partial images.

Yepp, agreed.

**Comment by ahachete** [comment]
> Another issue with the response model is that addons section is inside of the flavor version section. Instead, the addons section should be moved to the main section like flavor and base.

Yes, please, let's do this. I saw it and didn't comment as I had doubts whether addons may be at some point dependent on the flavor. But I'm pretty sure they are not, and if you confirm it, we're then both on the same page and so they should be relocated as said.

**Comment by teoincontatto** [comment]
> I have just one concern: the hash map. Having dynamic keys is not convenient on some languages (e.g. Java) as keys are not predictable (sure, it's doable, but not ideal). We can either leave it as-is, or nest them into a proper object with a fixed key as in:
> ...
> Note that name and data here could be renamed if desired. While I lean towards this solution with fixed keys, I don't really have a horse in this race. Decide among you too what you prefer.

We could have the model you propose without the map and serialize it as a map when serializing. Does not seem a big deal to me.

**Comment by teoincontatto** [comment]
BTW should we also suppress `tshirtSize` from the response just like we will do for `flavorAndBaseOmmitted`?

**Comment by ahachete** [comment]
> > I have just one concern: the hash map. Having dynamic keys is not convenient on some languages (e.g. Java) as keys are not predictable (sure, it's doable, but not ideal). We can either leave it as-is, or nest them into a proper object with a fixed key as in:
> > ...
> > Note that name and data here could be renamed if desired. While I lean towards this solution with fixed keys, I don't really have a horse in this race. Decide among you too what you prefer.
> 
> We could have the model you propose without the map and serialize it as a map when serializing. Does not seem a big deal to me.

OK, good to know. It doesn't really matter to me. @lgarciaog you decide here what is more convenient for you, being the first consumer of this API.

**Comment by teoincontatto** [comment]
And one more thing, just lifting related. I would mode platforms section inside of image section in the proposed response model for the /image-url endpoint.

**Comment by ahachete** [comment]
> And one more thing, just lifting related. I would mode platforms section inside of image section in the proposed response model for the /image-url endpoint.

Actually I think that everything should be into the `image` object. First of all because it belongs there. Second because one convention adopted for all the REST API was that every response has to be wrapped in a single-property object (this is considered a best practice as allows easier parsing from JS). Other methods follow this principle and we should adopt it consistently.
