### ISSUE TITLE
[PGA Containers] Patroni selector

### ISSUE THREAD

**Issue by ahachete** [postgres-anywhere/pga.sh#8]
Currently, the Patroni selector is just a boolean. However, it should be a drop-down with the available versions.

**Comment by ahachete** [comment]
Given that Patroni may have `enable|disable` as well as `default|v1|v2|v3|...` that may be more than one control. One Enable|Disable as like now, plus a DropDown. Maybe it sounds too much, but we really need to distinguish between those two things. Other ideas welcomed.

**Comment by lgarciaog** [comment]
> Maybe it sounds too much, but we really need to distinguish between those two things. Other ideas welcomed.

My suggestion would be to show a single dropdown with the available versions. If none is selected, then Patroni is simply disabled. If users select a specific version then it's obviously enabled.

**Comment by ahachete** [comment]
> My suggestion would be to show a single dropdown with the available versions. If none is selected, then Patroni is simply disabled. If users select a specific version then it's obviously enabled.
> The "default" option in the dropdown would be "DISABLED"

But this negates the option of a "default" Patroni option, like we have with Postgres and the extensions.

At most, we could have "none", "default (4.0.0)" and all the versions, all as entries in the dropdown. I don't know if this is better than a toggle plus a dropdown.

But basically, I believe that if dropdowns have only versions and on top one "default", this pattern should be kept consistent. So we need an additional control to determine whether you want Patroni or not.

> Understanding that, in the future, we will have more than one addon. When that time comes, we could create a table just like the one we have for the extensions, where we list all addons together with their available versions + their description + a checkbox to enable/disable.

I'm also a bit unsure about this. Addons will be quite limited (a few at most) and a table seems to be too much. I'd be more inclined to a similar pattern: a radio to select the addon, and a dropdown with the versions (included a "default version" option) or something like this.

**Comment by jjmaestro** [comment]
Currently, the UX is "jumpy", when clicking enable-disable, the Patroni Version dropdown appears and it pushes the Patronenable-disable toggle.

IMO I'd go with either a dropdown with "None" as first option (equivalent to disable) or the current "enable/disable" toggle but then I'd still show the Patroni Version dropdown in a "disabled state" (grayed out or something like that).

**Comment by ahachete** [comment]
> Currently, the UX is "jumpy", when clicking enable-disable, the Patroni Version dropdown appears and it pushes the Patronenable-disable toggle.
> 
> IMO I'd go with either a dropdown with "None" as first option (equivalent to disable) or the current "enable/disable" toggle but then I'd still show the Patroni Version dropdown in a "disabled state" (grayed out or something like that) to avoid the "jumpy" UX.

I agree, I'm more on the latter option (enable/disable vs dropdown grayed out if disabled).
